posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name = 'main_post_view'),
    path('liked/', like_unlike_post, name = 'like_post_view'),
    path('<pk>/update/', PostUpdateView.as_view(), name = 'post_update'),
    path('<pk>/delete/', PostDeleteView.as_view(), name = 'post_delete'),




]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    invites_received_view, 
    profiles_list_view, 
    invite_profiles_list_view,
    ProfileListView,
    send_invitation,
    remove_from_friends,
    ProfileDetailView,
    accept_invitation,
    reject_invitation,



)

app_name = 'profiles'

urlpatterns = [
    path('my-profile/', my_profile_view, name = 'my_profile'),
    path('my-invites/', invites_received_view, name = 'my_invites'),
    path('all-profiles/', ProfileListView.as_view(), name = 'all_profiles'),
    path('to-invite/', invite_profiles_list_view, name = 'invite_profiles'),
    path('send-invite/', send_invitation, name = 'send_invite'),
    path('remove-friend/', remove_from_friends, name = 'remove_friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invitation, name = 'accept_invite'),
    path('my-invites/reject/', reject_invitation, name = 'reject_invite'),



]

talkygram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name = 'home'),
    
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace = 'profiles')),
    path('posts/', include('posts.urls', namespace = 'posts')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css ADD HERE-->
    
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <link rel="stylesheet" type='text/css' href="{% static 'style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>talkygram - {% block title %}{% endblock title %}</title>
  </head>
  <body>
     <div class="ui inverted menu nav mb-7">
        <div class="ui container">
            <a href="{% url 'home' %}" class="item">
                <h3>Talkygram</h3>
            </a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'home' %}" class="item">
                Home
            </a>
            {% endif %}
            <a href="{% url 'posts:main_post_view' %}" class="item">
                Posts
            </a>
            

            <div class="right menu">
                {% if request.user.is_authenticated %}
                <div class="item">
                    <div class="ui teal buttons">
                        <div class="ui button">Friends</div>
                        <div class="ui simple dropdown icon button">
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                <a href="{% url 'profiles:all_profiles' %}" class="item">
                                    Add Friends
                                </a>
                                <a href="{% url 'profiles:invite_profiles' %}" class="item">
                                    Requests Sent
                                </a>
                                <a href="{% url 'profiles:my_invites' %}" class="item">
                                    Friends requests &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                                </a>
                            </div>
                        </div>
                    </div>
                    
                </div>
                    <div class="item">
                    <form action="" method="GET">
                        <div class="ui action left icon input">
                        <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                        <i class="search icon"></i>
                        <button type='submit' class="ui button">Search</button>
                        </div>
                    </form>
                    </div>
                    <a href="{% url 'profiles:my_profile' %}" class="item">
                        <img src={{picture.url}} class="ui avatar image">&nbsp;
                        {{ request.user }}
                    </a>

                    <a href="{% url 'account_logout' %}" class="ui item">
                        Logout
                    </a>
                {% else %}
                <a href="{% url 'account_login' %}" class="ui item">
                        Login
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="ui container">

      {% block content %}
      {% endblock content %}

    </div>


    {% block scripts %}
    {% endblock scripts %}
   
   <script type ="text/javascript" src={% static 'main.js' %}></script>


  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
<h1>{{user}}</h1>


{% endblock content %}



{% block scripts %}

<script>
$(document).ready(function(){
    console.log('working')
})

</script>


{% endblock scripts %}
   